addons:
  postgresql: 9.6
  # code_climate:
  #     repo_token: <Get from Code Climate>
# after_success:
#   - bundle exec codeclimate-test-reporter
language: ruby
rvm:
  - 2.4.1
before_script:
  - bundle exec rails db:setup
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
